paths:
  uploads: public/images
  static: public
collections_config:
  posts:
    path: src/content/blog
    output: false
    description: ''
    icon: notes
    preview:
    _editables:
      image:
        correct_orientation: true
        expandable: true
        height:
        image_size_attributes: true
        mime_type:
        paths:
        resize_style: contain
        width:
      content:
        blockquote:
        bold:
        bulletedlist:
        center:
        code:
        copyformatting:
        correct_orientation:
        embed:
        expandable:
        format:
        height:
        horizontalrule:
        image:
        image_size_attributes: true
        indent:
        italic:
        justify:
        left:
        link:
        mime_type:
        numberedlist:
        outdent:
        paths:
        redo:
        removeformat:
        resize_style: contain
        right:
        snippet:
        strike:
        styles:
        subscript:
        superscript:
        table:
        underline:
        undo:
        width:
    _enabled_editors:
      - content
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
    schema_key: _schema
  site_data:
    path: src/data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schema_key: _schema
  pages:
    path: src/content/pages
    output: true
    url: /[slug]/
    icon: notes
    _editables: {}
    _enabled_editors:
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
    schema_key: _schema
_inputs:
  src:
    type: image
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
