paths:
  uploads: public/images
  static: public
collections_config:
  posts:
    path: src/content/blog
    output: false
    description: ''
    icon: notes
    _editables:
      image:
        correct_orientation:
        expandable:
        height:
        image_size_attributes: true
        mime_type:
        paths:
        resize_style: contain
        width:
    _enabled_editors:
      - visual
      - content
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
    schema_key: _schema
  site_data:
    path: src/data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schema_key: _schema
  pages:
    path: src/content/pages
    output: true
    url: /[slug]/
    icon: notes
    _editables: {}
    _enabled_editors:
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
    schema_key: _schema
_inputs:
  src:
    type: image
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
